// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/capability.proto

package capability

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CapabilityService_GetData_FullMethodName       = "/capability.CapabilityService/GetData"
	CapabilityService_ExecuteAction_FullMethodName = "/capability.CapabilityService/ExecuteAction"
)

// CapabilityServiceClient is the client API for CapabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio genérico para exponer capacidades de dominio
type CapabilityServiceClient interface {
	// GetData: Para consultas de lectura (Read).
	// Permite obtener datos de entidades como 'concepts', 'capabilities', etc.
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
	// ExecuteAction: Para comandos de escritura (Write).
	// Permite ejecutar acciones como 'register_transaction', 'update_user', etc.
	ExecuteAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
}

type capabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapabilityServiceClient(cc grpc.ClientConnInterface) CapabilityServiceClient {
	return &capabilityServiceClient{cc}
}

func (c *capabilityServiceClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, CapabilityService_GetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilityServiceClient) ExecuteAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, CapabilityService_ExecuteAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapabilityServiceServer is the server API for CapabilityService service.
// All implementations must embed UnimplementedCapabilityServiceServer
// for forward compatibility.
//
// Servicio genérico para exponer capacidades de dominio
type CapabilityServiceServer interface {
	// GetData: Para consultas de lectura (Read).
	// Permite obtener datos de entidades como 'concepts', 'capabilities', etc.
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
	// ExecuteAction: Para comandos de escritura (Write).
	// Permite ejecutar acciones como 'register_transaction', 'update_user', etc.
	ExecuteAction(context.Context, *ActionRequest) (*ActionResponse, error)
	mustEmbedUnimplementedCapabilityServiceServer()
}

// UnimplementedCapabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapabilityServiceServer struct{}

func (UnimplementedCapabilityServiceServer) GetData(context.Context, *GetDataRequest) (*GetDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedCapabilityServiceServer) ExecuteAction(context.Context, *ActionRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteAction not implemented")
}
func (UnimplementedCapabilityServiceServer) mustEmbedUnimplementedCapabilityServiceServer() {}
func (UnimplementedCapabilityServiceServer) testEmbeddedByValue()                           {}

// UnsafeCapabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapabilityServiceServer will
// result in compilation errors.
type UnsafeCapabilityServiceServer interface {
	mustEmbedUnimplementedCapabilityServiceServer()
}

func RegisterCapabilityServiceServer(s grpc.ServiceRegistrar, srv CapabilityServiceServer) {
	// If the following call pancis, it indicates UnimplementedCapabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapabilityService_ServiceDesc, srv)
}

func _CapabilityService_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapabilityService_ExecuteAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).ExecuteAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_ExecuteAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).ExecuteAction(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapabilityService_ServiceDesc is the grpc.ServiceDesc for CapabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capability.CapabilityService",
	HandlerType: (*CapabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _CapabilityService_GetData_Handler,
		},
		{
			MethodName: "ExecuteAction",
			Handler:    _CapabilityService_ExecuteAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/capability.proto",
}
