// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/capability.proto

package capability

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nombre de la entidad a consultar (ej: "concepts", "transactions")
	EntityName string `protobuf:"bytes,1,opt,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	// Parámetros de filtrado en formato JSON string
	QueryParams   string `protobuf:"bytes,2,opt,name=query_params,json=queryParams,proto3" json:"query_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	mi := &file_proto_capability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_capability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_capability_proto_rawDescGZIP(), []int{0}
}

func (x *GetDataRequest) GetEntityName() string {
	if x != nil {
		return x.EntityName
	}
	return ""
}

func (x *GetDataRequest) GetQueryParams() string {
	if x != nil {
		return x.QueryParams
	}
	return ""
}

type GetDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Payload de respuesta en formato JSON o TOON
	DataPayload   string `protobuf:"bytes,1,opt,name=data_payload,json=dataPayload,proto3" json:"data_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataResponse) Reset() {
	*x = GetDataResponse{}
	mi := &file_proto_capability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataResponse) ProtoMessage() {}

func (x *GetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_capability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataResponse.ProtoReflect.Descriptor instead.
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_capability_proto_rawDescGZIP(), []int{1}
}

func (x *GetDataResponse) GetDataPayload() string {
	if x != nil {
		return x.DataPayload
	}
	return ""
}

type ActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nombre de la acción a ejecutar (ej: "register_transaction")
	ActionName string `protobuf:"bytes,1,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	// Datos necesarios para la acción en formato JSON string
	Payload       string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_proto_capability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_capability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_capability_proto_rawDescGZIP(), []int{2}
}

func (x *ActionRequest) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *ActionRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ActionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indica si la acción fue exitosa
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Mensaje descriptivo o de error
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Datos resultantes opcionales en formato JSON string
	DataPayload   string `protobuf:"bytes,3,opt,name=data_payload,json=dataPayload,proto3" json:"data_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_proto_capability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_capability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_capability_proto_rawDescGZIP(), []int{3}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActionResponse) GetDataPayload() string {
	if x != nil {
		return x.DataPayload
	}
	return ""
}

var File_proto_capability_proto protoreflect.FileDescriptor

const file_proto_capability_proto_rawDesc = "" +
	"\n" +
	"\x16proto/capability.proto\x12\n" +
	"capability\"T\n" +
	"\x0eGetDataRequest\x12\x1f\n" +
	"\ventity_name\x18\x01 \x01(\tR\n" +
	"entityName\x12!\n" +
	"\fquery_params\x18\x02 \x01(\tR\vqueryParams\"4\n" +
	"\x0fGetDataResponse\x12!\n" +
	"\fdata_payload\x18\x01 \x01(\tR\vdataPayload\"J\n" +
	"\rActionRequest\x12\x1f\n" +
	"\vaction_name\x18\x01 \x01(\tR\n" +
	"actionName\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"g\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fdata_payload\x18\x03 \x01(\tR\vdataPayload2\x9f\x01\n" +
	"\x11CapabilityService\x12B\n" +
	"\aGetData\x12\x1a.capability.GetDataRequest\x1a\x1b.capability.GetDataResponse\x12F\n" +
	"\rExecuteAction\x12\x19.capability.ActionRequest\x1a\x1a.capability.ActionResponseB\x1bZ\x19github.com/Mozart-SymphonIA/infra-mz/proto/capabilityb\x06proto3"

var (
	file_proto_capability_proto_rawDescOnce sync.Once
	file_proto_capability_proto_rawDescData []byte
)

func file_proto_capability_proto_rawDescGZIP() []byte {
	file_proto_capability_proto_rawDescOnce.Do(func() {
		file_proto_capability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_capability_proto_rawDesc), len(file_proto_capability_proto_rawDesc)))
	})
	return file_proto_capability_proto_rawDescData
}

var file_proto_capability_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_capability_proto_goTypes = []any{
	(*GetDataRequest)(nil),  // 0: capability.GetDataRequest
	(*GetDataResponse)(nil), // 1: capability.GetDataResponse
	(*ActionRequest)(nil),   // 2: capability.ActionRequest
	(*ActionResponse)(nil),  // 3: capability.ActionResponse
}
var file_proto_capability_proto_depIdxs = []int32{
	0, // 0: capability.CapabilityService.GetData:input_type -> capability.GetDataRequest
	2, // 1: capability.CapabilityService.ExecuteAction:input_type -> capability.ActionRequest
	1, // 2: capability.CapabilityService.GetData:output_type -> capability.GetDataResponse
	3, // 3: capability.CapabilityService.ExecuteAction:output_type -> capability.ActionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_capability_proto_init() }
func file_proto_capability_proto_init() {
	if File_proto_capability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_capability_proto_rawDesc), len(file_proto_capability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_capability_proto_goTypes,
		DependencyIndexes: file_proto_capability_proto_depIdxs,
		MessageInfos:      file_proto_capability_proto_msgTypes,
	}.Build()
	File_proto_capability_proto = out.File
	file_proto_capability_proto_goTypes = nil
	file_proto_capability_proto_depIdxs = nil
}
